### ISSUE TITLE
Création d'intervention

### ISSUE THREAD

**Issue by vmpikaso** [Ginkishi/ProjetArchi#2]
Création d'une intervention grâce à un formulaire

**Comment by vmpikaso** [comment]
@yasminehadjout : Je vais te créer une branche pour toi, comme ça tu pourras y mettre tes modifications.

**Comment by yasminehadjout** [comment]
Elles dérangent la branche principale ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by vmpikaso** [comment]
@yasminehadjout : Oui et non, juste que je modifie certains fichiers que tu remodifies derrière XD. Après je dois refaire la même chose XP

**Comment by vmpikaso** [comment]
@yasminehadjout  : Cela te permettra de créer tes propres modifs sans toucher à mes modifs XP

**Comment by yasminehadjout** [comment]
Comme ? Attends après on en parle , je vois pas ce que j'ai modifié de dérangeant pour toi

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by yasminehadjout** [comment]
Et après on fait comment pour tout coller :/ à la fin du cours on en reparle

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by vmpikaso** [comment]
@yasminehadjout tkt rien de grave X)
