### ISSUE TITLE
Modification du formulaire d'ajout d'intervention

### ISSUE THREAD

**Issue by vmpikaso** [Ginkishi/ProjetArchi#27]
Je viens modifier le design de la page d'ajout, il faudra que tu la modifie pour que tu y rajoute la possibilité de d'ajouter, de rajouter plusieurs véhicule
Désolé pour la gêne occasionné X)

**Comment by yasminehadjout** [comment]
ة
C'est Lilian qui voulait le faire non ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by yasminehadjout** [comment]
Ahhh oups j'ai mal lu je pensais que tu avais écris modifications d'interventions ouki ouki

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by vmpikaso** [comment]
Essaye de faire les modifications sur cette branche X) @yasminehadjout

**Comment by yasminehadjout** [comment]
yup c'est ce que je fais la :p
